name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmemcached-dev memcached
    - name: Start memcached daemons
      run: |
        memcached -d -p 11211
        memcached -d -p 11212
        memcached -d -p 11213
    - name: Add memcached host to /etc/hosts
      run: |
        echo "127.0.0.1 memcached" | sudo tee -a /etc/hosts
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
