name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libmemcached-dev memcached
    - name: Start memcached daemon 1
      run: |
        memcached -d -p 11211
    - name: Start memcached daemon 2
      run: |
        memcached -d -p 11212
    - name: Start memcached daemon 3
      run: |
        memcached -d -p 11213
    - name: Add memcached host to /etc/hosts
      run: |
        echo "127.0.0.1 memcached" | sudo tee -a /etc/hosts
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
